### ISSUE TITLE
Missing files under Plex2Sonos.HostingConsole

### ISSUE THREAD

**Issue by jamietre** [aceven24/Plex2Sonos#1]
Looks like some stuff missing from repo...

```
Could not find file '..\Plex2Sonos\Plex2Sonos.HostingConsole\Plex2Sonos.HostingConsole.csproj'
```

**Comment by aceven24** [comment]
Stupid studio give me a few

Andy

On Sep 2, 2015, at 6:53 PM, James Treworgy <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like some stuff missing from repo...

Could not find file '..\Plex2Sonos\Plex2Sonos.HostingConsole\Plex2Sonos.HostingConsole.csproj'

**Comment by aceven24** [comment]
Fixed, make sure you search and replace my IP address for the image thumbnails.. The class model is all over the place right now as well it was just a brain dump of ideas with no direction, but maybe we can grab lunch and create a proper class diagram..

**Comment by jamietre** [comment]
Sounds good, going to try to get this fired up tonight. What do you think about trying to get the nodejs project off the ground soon? Since you basically already have the POC working maybe we should start implementing it cross platform rather than continuing C# development as we refine it. 

I say "we" like I have done anything yet :)

**Comment by jamietre** [comment]
BTW you should edit the comment you replied from your email, since it has your phone # in the footer!

**Comment by aceven24** [comment]
Yeah I saw that, rookie GitHub mistake replying from my phone.  I'm down with going the node.js route, the only thing I need to really understand is the whole client concept we talked about on the C# side.  I think the interaction with Plex would be trivial, there already several Plex packages on node.  I'd rather learn node than get the rust off my C# skills, but you would have to be patient with me as I don't want it to go from we as me to we as in just you.

**Comment by jamietre** [comment]
Well I know a lot about Javascript generally but don't have a ton of experience with the node platform either. But I feel the same way, I would rather fight these battles in a platform I'm interested in learning, and create code that will be cross-platform compatible. Should be a great way to cut our teeth in node with an interesting and useful project. I feel like I know enough to get the project framework set up, I can try to put something together over the next few days and we can go from there.

**Comment by aceven24** [comment]
Ok sounds good, I'm going to dig a bit more into the plex side.. the Sonos side is pretty straight forward.  I'll look into some SOAP packages for node, I'm sure they exist.. Why Sonos went with SOAP is beyond me..

**Comment by jamietre** [comment]
Sonos is older than methuselah, prob Soap made sense at the time and they don't want to break the API.

**Comment by jamietre** [comment]
You are so crazy with all your protocol buffers. I got it working... took a
bit because it choked on something in my library, eventually I just cut it
off at 10 albums and it works fine. It seems like there is something crazy
with the data structures, C# definitely less well suited to deal with it
than JS, as the error handling is ugly right now, and would require a lot
of exception based code to deal with missing/optional fields in the data
structures. Seems like there is something wierd about the way it requests
the artist/album data, it's really slow and looking at the data in fiddler
looks like a lot of stuff being repeated. But details, it basically works,
nice job. Going to bed now..

Almost got it going. I set up the Sonos config and added it to my client,
but it wouldn't connect. It adds about 20 or so albums and then starts the
server.. not sure if this is an artificial limt to keep things sane for
testing or what, but there is definitely something odd about how the data
is being pulled and it's ungodly slow, not sure if its my network or Plex
or what. Does this look normal? The data being returned by those children
requests seems kind of weird, it keeps going deeper into the same artist
and returning incomplete structures which causes the dynamic parser to keep
choking (with caught errors).

Anyway not a big deal, the real problem is I can't seem to figure out why
SONOS can't connect. Nothing happens... just says it can't connect.
Verified I can connect from another PC in my network. I changed the port to
30020 because 8888 was being used by chrome for some stuff.  This is the
end of the console log (I added some progress logging)

Adding 'Annie Lennox'
...1 albums
Adding 'Antoine Silverman'
...1 albums
Adding 'Anton Hughes'
Finished Loading Plex Data
Plex2Sonos is live now at http://176.16.2.143:30020/Plex2Sonos
ImageService is live now at http://176.16.2.143:30020/ImageService
Press the "Any Key" To Close

#ResultProtocolHostURLBodyCachingContent-TypeProcessCommentsCustom9200HTTP
176.16.2.10:32400/library/sections/1/all551,021no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32010200HTTP176.16.2.10:32400
/library/metadata/130/children1,872no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32011200HTTP176.16.2.10:32400
/library/metadata/131/children14,184no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32012200HTTP176.16.2.10:32400
/library/metadata/146/children12,086no-cacheapplication/json
plex2sonos.hostingconsole.vshost:320

**Comment by aceven24** [comment]
The dynamic rest client is dog slow in debug mode even with the debugger not connected.  To populate the whole db you need to compile and run in release mode.  I didn't think I had duplicative requests but who knows.  So I'm confused did you get it to play via sonos or not?

Yes I was laughing when I put in that function to extract data and catch the exception and return null or some default value.. I was like why am I doing dynamic crap in c#, but I was too lazy to build the json objects.

On Sep 3, 2015, at 12:26 AM, James Treworgy <notifications@github.com<mailto:notifications@github.com>> wrote:

You are so crazy with all your protocol buffers. I got it working... took a
bit because it choked on something in my library, eventually I just cut it
off at 10 albums and it works fine. It seems like there is something crazy
with the data structures, C# definitely less well suited to deal with it
than JS, as the error handling is ugly right now, and would require a lot
of exception based code to deal with missing/optional fields in the data
structures. Seems like there is something wierd about the way it requests
the artist/album data, it's really slow and looking at the data in fiddler
looks like a lot of stuff being repeated. But details, it basically works,
nice job. Going to bed now..

Almost got it going. I set up the Sonos config and added it to my client,
but it wouldn't connect. It adds about 20 or so albums and then starts the
server.. not sure if this is an artificial limt to keep things sane for
testing or what, but there is definitely something odd about how the data
is being pulled and it's ungodly slow, not sure if its my network or Plex
or what. Does this look normal? The data being returned by those children
requests seems kind of weird, it keeps going deeper into the same artist
and returning incomplete structures which causes the dynamic parser to keep
choking (with caught errors).

Anyway not a big deal, the real problem is I can't seem to figure out why
SONOS can't connect. Nothing happens... just says it can't connect.
Verified I can connect from another PC in my network. I changed the port to
30020 because 8888 was being used by chrome for some stuff. This is the
end of the console log (I added some progress logging)

Adding 'Annie Lennox'
...1 albums
Adding 'Antoine Silverman'
...1 albums
Adding 'Anton Hughes'
Finished Loading Plex Data
Plex2Sonos is live now at http://176.16.2.143:30020/Plex2Sonos
ImageService is live now at http://176.16.2.143:30020/ImageService
Press the "Any Key" To Close

#ResultProtocolHostURLBodyCachingContent-TypeProcessCommentsCustom9200HTTP
176.16.2.10:32400/library/sections/1/all551,021no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32010200HTTP176.16.2.10:32400
/library/metadata/130/children1,872no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32011200HTTP176.16.2.10:32400
/library/metadata/131/children14,184no-cacheapplication/json
plex2sonos.hostingconsole.vshost:32012200HTTP176.16.2.10:32400
/library/metadata/146/children12,086no-cacheapplication/json
plex2sonos.hostingconsole.vshost:320

**Comment by jamietre** [comment]
Yeah I got it to work. I didn't have time to get into the data structure issues so I just cut it off at 10 artists (before it crashed) and it worked fine. (After I turned on debugging and saw it was getting exceptions on basically every other album I got scared ;)

But the problems don't seem like a big deal, there just seem to be either optional fields that are not returned, or you are looking at the wrong node on certain structures, couldn't quite tell what was going on at midnight but it totally works.

So now we need to make some decisions for nodejs... I think the SONOS part should be completely generic and expose an evented API that anything can consume. The Plex part can be implemented as a plugin for a general purpose middleman server. We need a data store, this should probably also be generic, we can just start a completely memory-based implentation like the one you have now (that caches its metadata of course). It should probably be set up to automatically sync with the source server... not sure if Plex has a "recently updated" API or not. If not then we would have to periodically quesry all the metadata.

Anyway lots of fun stuff to do, but if we just create a nice clean architecture and API first we can do trivial implementations for everything and make them better over time...

**Comment by jamietre** [comment]
BTW - create a rooom on http://gitter.im -- better for random banter than issues.

And check this out, should come in handy

https://github.com/dereulenspiegel/Sonos-Node-API

**Comment by aceven24** [comment]
Totally agree on making the sonos part a generic interface that various sources implement a pluggable interface.

Yes, plex has a last updated date at every level and it cascades up.  So if one track changed in one album, you can do selective updates.  I do write out a compressed protobuf file and there are some things I think we could go back to plex for in real time, like summary about artist, album etc as that is what causes bloat to the file.

I think that plex might even have a push notification for sending clients info on changes but I haven't looked deep into that.

Your music collection is it the classic one or the new on available only to plexpass

Andy

On Sep 3, 2015, at 8:25 AM, James Treworgy <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah I got it to work. I didn't have time to get into the data structure issues so I just cut it off at 10 artists (before it crashed) and it worked fine. (After I turned on debugging and saw it was getting exceptions on basically every other album I got scared ;)

But the problems don't seem like a big deal, there just seem to be either optional fields that are not returned, or you are looking at the wrong node on certain structures, couldn't quite tell what was going on at midnight but it totally works.

So now we need to make some decisions for nodejs... I think the SONOS part should be completely generic and expose an evented API that anything can consume. The Plex part can be implemented as a plugin for a general purpose middleman server. We need a data store, this should probably also be generic, we can just start a completely memory-based implentation like the one you have now (that caches its metadata of course). It should probably be set up to automatically sync with the source server... not sure if Plex has a "recently updated" API or not. If not then we would have to periodically quesry all the metadata.

Anyway lots of fun stuff to do, but if we just create a nice clean architecture and API first we can do trivial implementations for everything and make them better over time...
